[server]
headless = true
#port = 8501
enableCORS = true
enableXsrfProtection = true
#address = "0.0.0.0"

[theme]
base = "light"
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
font = "sans serif"

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[client]
showErrorDetails = true
toolbarMode = "auto"